name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  
  build_cmake:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install bash
      run: sudo apt install bash
    - name: install cmake
      run: sudo apt install cmake
    - name: install git
      run: sudo apt install git
    - name: create build in cmake
      run: cmake -S kunai-lib/ -B build -D CMAKE_BUILD_TYPE=DEBUG -D UNIT_TESTING=ON
    - name: build with cmake
      run: cmake --build build -j
    - name: Run testing
      run: ctest --test-dir build/ --output-on-failure